name = "Homie Pack"
author = "Kraka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7427bc46d16edea55fd8c209c1eb9f39c634ac7e54d2663189c51f17bbf7cf38"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"
