name = "Homie Pack"
author = "Kraka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c72e55aaee263959cb9881df6d3624428155ed9e86a82333a06dd3aa61034df"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"
