name = "Homie Pack"
author = "Kraka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b09d20f2a10433de1e90b7ab636416828bb605082995aefd949d16f44926c288"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"
